// Actual local Edge: deterministic promise barriers, fictional state, no provider calls.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{spawn}=require('child_process');
const root=__dirname,results=[],server=spawn('python',['-u','-B','-X','utf8','-m','http.server','62397','--bind','127.0.0.1','--directory',root],{windowsHide:true,stdio:'pipe'});
const file=path.join(root,'fictional-B.json');fs.writeFileSync(file,JSON.stringify({id:'B',text:'Incoming B'})+'\n');
let browser;
async function gate(p,stage,id=1){await p.waitForFunction(([s,n])=>window.fixture?.gates().includes(n+':'+s),[stage,id]);}
async function release(p,stage,id=1,fail=false){await p.evaluate(([s,n,f])=>window.fixture.release(s,f,n),[stage,id,fail]);}
async function settled(p,id=1){await p.waitForFunction(n=>window.fixture.operations().some(x=>x.id===n&&x.settled),id);}
async function state(p){return p.evaluate(()=>window.fixture.snapshot());}
async function load(p){await p.locator('#file').setInputFiles(file);await gate(p,'read');}
async function toValidation(p,id=1){await release(p,'read',id);await gate(p,'validate',id);}
async function success(p,id=1){await toValidation(p,id);await release(p,'validate',id);await settled(p,id);}
async function trial(name,params,fn,expectMutation=false){const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));try{await page.goto('http://127.0.0.1:62397/fixture.html?'+new URLSearchParams(params));await fn(page);assert.deepEqual(errors,[]);results.push({name,passed:true,kind:expectMutation?'dangerous mutation detected':'matched control',state:await state(page),trace:await page.evaluate(()=>window.fixture.trace())});}catch(e){results.push({name,passed:false,error:e.stack,errors,state:await state(page).catch(()=>null)});}finally{await page.close();}}
(async()=>{try{
 await new Promise((resolve,reject)=>{let text='';server.stdout.on('data',d=>{text+=d;if(text.includes('Serving HTTP'))resolve();});server.stderr.on('data',d=>{text+=d;if(text.includes('Serving HTTP'))resolve();});server.on('exit',c=>reject(Error('Server exited '+c)));setTimeout(()=>reject(Error('Server startup not observed')),5000).unref();});
 browser=await chromium.launch({channel:'msedge',headless:true});
 await trial('new draft while replacement waits is retained when discard rejected',{},async p=>{await load(p);await p.locator('#draft').fill('NEW A');await toValidation(p);await release(p,'validate');await p.locator('#reject').click();await settled(p);assert.equal((await state(p)).draft,'NEW A');assert.equal((await state(p)).active,'A');});
 await trial('current discard consent permits one useful replacement',{},async p=>{await load(p);await p.locator('#draft').fill('NEW A');await toValidation(p);await release(p,'validate');await p.locator('#accept').click();await settled(p);const s=await state(p);assert.equal(s.active,'B');assert.equal(s.commits,1);assert.equal(s.records.B,'Incoming B');});
 await trial('edit during asynchronous confirmation invalidates earlier choice',{},async p=>{await load(p);await p.locator('#draft').fill('A first draft');await toValidation(p);await release(p,'validate');await p.locator('#accept').waitFor({state:'visible'});await p.locator('#draft').fill('A newer draft');await p.locator('#accept').click();await settled(p);const s=await state(p);assert.equal(s.draft,'A newer draft');assert.equal(s.active,'A');assert.equal(s.commits,0);});
 await trial('cancel then late completion preserves draft and same-file retry succeeds',{},async p=>{await p.locator('#draft').fill('A draft');await load(p);await toValidation(p);await p.locator('#cancel').click();await release(p,'validate');await settled(p);assert.equal((await state(p)).draft,'A draft');assert.equal(await p.locator('#file').inputValue(),'');await p.locator('#file').setInputFiles(file);await gate(p,'read',2);await toValidation(p,2);await release(p,'validate',2);await p.locator('#accept').click();await settled(p,2);assert.equal((await state(p)).active,'B');assert.equal((await state(p)).commits,1);});
 await trial('read failure preserves work and same file retry succeeds',{},async p=>{await load(p);await release(p,'read',1,true);await settled(p);assert.equal((await state(p)).records.A,'Original A');await p.locator('#file').setInputFiles(file);await gate(p,'read',2);await success(p,2);assert.equal((await state(p)).active,'B');});
 await trial('record switch invalidates old replacement',{},async p=>{await load(p);await toValidation(p);await p.locator('#openC').click();await p.locator('#draft').fill('C belongs here');await release(p,'validate');await settled(p);assert.equal((await state(p)).active,'C');assert.equal((await state(p)).draft,'C belongs here');});
 await trial('valid replacement rebinds editor so old draft cannot write to B',{},async p=>{await p.locator('#draft').fill('A old editor');await load(p);await toValidation(p);await release(p,'validate');await p.locator('#accept').click();await settled(p);assert.equal((await state(p)).draft,'');assert.equal((await state(p)).editor,'B');await p.locator('#draft').fill('B legitimate edit');await p.locator('#apply').click();assert.equal((await state(p)).records.B,'B legitimate edit');});
 await trial('serialized UI holds real editing and navigation through final await',{mode:'serialized'},async p=>{await p.locator('#draft').fill('A retained');await load(p);await toValidation(p);assert.equal((await state(p)).inert,true);await p.locator('#draft').click({force:true});await p.keyboard.type('BAD');await p.locator('#openC').click({force:true});let s=await state(p);assert.equal(s.draft,'A retained');assert.equal(s.active,'A');assert.equal(s.pendingVisible,true);assert.equal(await p.locator('#pending').isVisible(),true);await p.screenshot({path:path.join(root,'serialized-pending.png')});await release(p,'validate');await p.locator('#reject').click();await settled(p);assert.equal((await state(p)).inert,false);await p.locator('#draft').fill('Editing restored');assert.equal((await state(p)).draft,'Editing restored');});
 await trial('serialized failure and cancellation restore real controls',{mode:'serialized'},async p=>{await load(p);await release(p,'read',1,true);await settled(p);await p.locator('#draft').fill('After error');await p.locator('#file').setInputFiles(file);await gate(p,'read',2);await p.locator('#cancel').click();await release(p,'read',2);await settled(p,2);await p.locator('#draft').fill('After cancel');assert.equal((await state(p)).draft,'After cancel');assert.equal((await state(p)).pendingVisible,false);});
 await trial('save holds editable fields until commit and restores them',{},async p=>{await p.locator('#draft').fill('Saved A');await p.locator('#save').click();await gate(p,'read');await toValidation(p);await p.locator('#draft').click({force:true});await p.keyboard.type('Late lost edit');assert.equal((await state(p)).draft,'Saved A');await release(p,'validate');await settled(p);assert.equal((await state(p)).records.A,'Saved A');await p.locator('#draft').fill('Next edit');assert.equal((await state(p)).draft,'Next edit');});
 async function refreshRace(p,mutant){await p.locator('#refresh').click();await gate(p,'read');await toValidation(p);await p.locator('#draft').fill('A newly saved');await p.locator('#save').click();await gate(p,'read',2);await success(p,2);await release(p,'validate',1);await settled(p,1);const s=await state(p);assert.equal(s.records.A,'A newly saved');assert.equal(s.catalog.A,mutant?'Original A':'A newly saved');}
 await trial('older refresh cannot roll back display after a successful save',{},p=>refreshRace(p,false));
 await trial('invocation-only guard loses the later draft',{fault:'start_guard'},async p=>{await load(p);await p.locator('#draft').fill('NEW A');await success(p);const s=await state(p);assert.equal(s.active,'B');assert.equal(s.draft,'');assert.equal(s.commits,1);},true);
 await trial('cancel-dialog-only mutation still commits late result',{fault:'cancel_late'},async p=>{await load(p);await toValidation(p);await p.locator('#cancel').click();await release(p,'validate');await settled(p);assert.equal((await state(p)).active,'B');},true);
 await trial('old editor mutation applies A draft to B',{fault:'wrong_editor'},async p=>{await p.locator('#draft').fill('A old editor');await load(p);await toValidation(p);await release(p,'validate');await p.locator('#accept').click();await settled(p);await p.locator('#apply').click();assert.equal((await state(p)).records.B,'A old editor');},true);
 await trial('early unlock permits conflict during final validation',{mode:'serialized',fault:'early_unlock'},async p=>{await load(p);await toValidation(p);await p.locator('#draft').fill('EDIT DURING ALLEGED LOCK');assert.equal((await state(p)).inert,false);assert.equal((await state(p)).draft,'EDIT DURING ALLEGED LOCK');await release(p,'validate');await p.locator('#reject').click();await settled(p);},true);
 await trial('uncleared file input prevents same-file selection event',{fault:'same_file'},async p=>{await load(p);await toValidation(p);await p.locator('#cancel').click();await release(p,'validate');await settled(p);assert.notEqual(await p.locator('#file').inputValue(),'');await p.locator('#file').setInputFiles(file);assert.equal((await state(p)).request,1);},true);
 await trial('save-button-only guard permits and erases later correction',{fault:'save_edit'},async p=>{await p.locator('#draft').fill('Saved A');await p.locator('#save').click();await gate(p,'read');await toValidation(p);await p.locator('#draft').fill('Late correction');await release(p,'validate');await settled(p);const s=await state(p);assert.equal(s.draft,'');assert.equal(s.records.A,'Saved A');},true);
 await trial('old refresh snapshot replaces visible newly saved state',{fault:'stale_refresh'},p=>refreshRace(p,true),true);
 const report={kind:'actual Edge on isolated synthetic implementation, not model or estate product qualification',browser:browser.version(),checks:results.length,passed:results.filter(x=>x.passed).length,results};fs.writeFileSync(path.join(root,'browser-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({checks:report.checks,passed:report.passed,failures:results.filter(x=>!x.passed)},null,2));if(report.passed!==report.checks)process.exitCode=1;
 }catch(e){console.error(e);process.exitCode=1;}finally{if(browser)await browser.close();server.kill();}})();