'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const O=process.argv[2];assert(O&&!fs.existsSync(O));fs.mkdirSync(O,{recursive:true});
const source=path.join(__dirname,'fixture.html');const fixture=fs.readFileSync(source);fs.writeFileSync(path.join(O,'fixture.html'),fixture);const file=path.join(O,'fictional-B.json');fs.writeFileSync(file,JSON.stringify({id:'B',text:'Incoming B'}));
const server=http.createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(fixture)});let browser;const results=[];
const snap=p=>p.evaluate(()=>window.fixture.snapshot());
const gate=(p,s,id=1)=>p.waitForFunction(([s,id])=>window.fixture.gates().includes(id+':'+s),[s,id]);
const release=(p,s,id=1)=>p.evaluate(([s,id])=>window.fixture.release(s,false,id),[s,id]);
const settled=(p,id=1)=>p.waitForFunction(id=>window.fixture.operations().some(o=>o.id===id&&o.settled),id);
async function start(p){await p.locator('#file').setInputFiles(file);await gate(p,'read');await release(p,'read');await gate(p,'validate')}
async function complete(p,id=1){await release(p,'read',id);await gate(p,'validate',id);await release(p,'validate',id);await settled(p,id)}
async function trace(name,params,run,expected){const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));try{await page.goto('http://127.0.0.1:'+server.address().port+'/?'+new URLSearchParams(params));const observation=await run(page);assert.equal(observation.holds,expected,name);assert.deepEqual(errors,[]);results.push({name,variant:params,expected_invariant:expected,...observation,events:await page.evaluate(()=>window.fixture.trace())})}finally{await page.close()}}
const cases=[
 ['current-draft permission','start_guard',{},async p=>{await start(p);await p.locator('#draft').fill('NEW A');await release(p,'validate');await p.waitForFunction(()=>!document.querySelector('#confirm').hidden||window.fixture.operations()[0].settled);if(await p.locator('#reject').isVisible())await p.locator('#reject').click();await settled(p);const s=await snap(p);return {holds:s.active==='A'&&s.draft==='NEW A'&&s.commits===0,state:s}}],
 ['cancel remains invalid after completion','cancel_late',{},async p=>{await start(p);await p.locator('#cancel').click();await release(p,'validate');await settled(p);const s=await snap(p);return {holds:s.active==='A'&&s.commits===0&&s.records.A==='Original A',state:s}}],
 ['old editor cannot apply A draft to B','wrong_editor',{},async p=>{await p.locator('#draft').fill('A old editor');await start(p);await release(p,'validate');await p.locator('#accept').click();await settled(p);const before=await snap(p);await p.locator('#apply').click();const s=await snap(p);return {holds:before.commits===1&&before.editor==='B'&&s.records.B!=='A old editor',before,state:s}}],
 ['serialized lifetime reaches final validation','early_unlock',{mode:'serialized'},async p=>{await start(p);await p.locator('#draft').click({force:true});await p.keyboard.type('CONFLICT');await p.locator('#openC').click({force:true});const held=await snap(p);await release(p,'validate');await p.waitForFunction(()=>!document.querySelector('#confirm').hidden||window.fixture.operations()[0].settled);if(await p.locator('#reject').isVisible())await p.locator('#reject').click();await settled(p);const s=await snap(p);return {holds:held.inert&&held.pendingVisible&&held.active==='A'&&held.draft===''&&!s.inert,held,state:s}}],
 ['same-file retry is a new usable operation','same_file',{},async p=>{await start(p);await p.locator('#cancel').click();await release(p,'validate');await settled(p);await p.locator('#file').setInputFiles(file);const s=await snap(p);const retried=s.request===2;if(retried){await gate(p,'read',2);await complete(p,2)}const final=await snap(p);return {holds:retried&&final.active==='B'&&final.commits===1,state:final}}],
 ['save lifetime protects every draft field','save_edit',{},async p=>{await p.locator('#draft').fill('Saved A');await p.locator('#save').click();await gate(p,'read');await release(p,'read');await gate(p,'validate');await p.locator('#draft').click({force:true});await p.keyboard.type('LOST CORRECTION');const held=await snap(p);await release(p,'validate');await settled(p);const s=await snap(p);return {holds:held.draft==='Saved A'&&held.pendingVisible&&s.records.A==='Saved A'&&s.commits===1&&!s.inert,held,state:s}}],
 ['old read cannot contradict newer saved view','stale_refresh',{},async p=>{await p.locator('#refresh').click();await gate(p,'read');await release(p,'read');await gate(p,'validate');await p.locator('#draft').fill('A newly saved');await p.locator('#save').click();await gate(p,'read',2);await complete(p,2);await release(p,'validate');await settled(p);const s=await snap(p);return {holds:s.records.A==='A newly saved'&&s.catalog.A===s.records.A&&s.commits===1,state:s}}]
];
(async()=>{try{await new Promise(r=>server.listen(0,'127.0.0.1',r));browser=await chromium.launch({channel:'msedge',headless:true});for(const [name,fault,params,run] of cases){await trace(name+' protected',params,run,true);await trace(name+' broken',{...params,fault},run,false)}
await trace('current permission permits exactly one replacement',{},async p=>{await p.locator('#draft').fill('A draft');await start(p);await release(p,'validate');await p.locator('#accept').click();await settled(p);const s=await snap(p);return {holds:s.active==='B'&&s.records.B==='Incoming B'&&s.commits===1,state:s}},true);
await trace('new edit during asynchronous permission is preserved',{},async p=>{await p.locator('#draft').fill('First A');await start(p);await release(p,'validate');await p.locator('#accept').waitFor();await p.locator('#draft').fill('NEWER A');await p.locator('#accept').click();await settled(p);const s=await snap(p);return {holds:s.active==='A'&&s.draft==='NEWER A'&&s.commits===0,state:s}},true);
const result={status:'PASS',checks:results.length,protected:9,broken:7,engine:browser.version(),scope:'The identical invariant function runs on protected and broken fixtures; real pointer/keyboard operations and observable gates. Oracle qualification only, not estate product or model adherence.',fixture_sha256:require('crypto').createHash('sha256').update(fixture).digest('hex'),results};fs.writeFileSync(path.join(O,'results.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:'PASS',checks:result.checks}));
}catch(e){fs.writeFileSync(path.join(O,'failure.json'),JSON.stringify({error:e.stack,results},null,2));console.error(e);process.exitCode=1}finally{if(browser)await browser.close();await new Promise(r=>server.close(r))}})();